/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.ImageIcon;
import view.login;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import config.config;
import javax.swing.JOptionPane;
import view.siswa;
/**
 *
 * @author Ammar Dragneel
 */
public class edit_siswa extends javax.swing.JFrame {
    private void golet(){
       String nama = t_nama.getText();
        try {
             String sql = "select * from murid where nama = '"+nama+"'";
             Statement st = config.Conn().createStatement();
             ResultSet rs = st.executeQuery(sql);
              if (rs.next()) {
                String a = rs.getString("nis");
                String b = rs.getString("alamat");
                String c = rs.getString("jk");
                String d = rs.getString("ttl");
                String e = rs.getString("hp");
                
                               
                t_nis.setText(a);
                t_alamat.setText(b);
                t_lahir.setText(d);
              
                t_hp.setText(e);
                 if (c.equals("l")) {
                        l.setSelected(true);
                    }else {
                        p.setSelected(true);
                    }
                
                
                
            } else {
                JOptionPane.showMessageDialog(null, "ora ketemu");
            }

             
        } catch (Exception e) {
            System.out.println(e);
        }
       
        
       
    }
    private void update () {
        String nis = t_nis.getText();
        String nama = t_nama.getText();
        String alamat = t_alamat.getText();
        String hp = t_hp.getText();
        String ttl = t_lahir.getText();
        String jk = " ";
        if (l.isSelected()) {
           jk="l";
        } else if (p.isSelected()) {
           jk="p";
        }
        try {
            String sql = "update murid set nis ='"+nis+"', nama ='"+nama+"', alamat ='"+alamat+"', jk='"+jk+"', ttl='"+ttl+"',hp='"+hp+"' where nama ='"+nama+"'";
            Statement st = config.Conn().createStatement();
            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(null,"Update Sukses gan");
            
        } catch (Exception e) {
            System.out.println(e);
        }
        
    
    }
    /**
     * Creates new form edit_guru
     */
    public edit_siswa() {
        initComponents();
        initComponents();
         ImageIcon icon = new ImageIcon("src/view/logo.png");
         setIconImage(icon.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        a = new javax.swing.JLabel();
        t_nis = new javax.swing.JTextField();
        t_nama = new javax.swing.JTextField();
        a5 = new javax.swing.JLabel();
        a1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        t_alamat = new javax.swing.JTextArea();
        a2 = new javax.swing.JLabel();
        l = new javax.swing.JRadioButton();
        p = new javax.swing.JRadioButton();
        a4 = new javax.swing.JLabel();
        a3 = new javax.swing.JLabel();
        t_hp = new javax.swing.JTextField();
        btn_insert = new javax.swing.JButton();
        btn_insert1 = new javax.swing.JButton();
        t_lahir = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Edit Profile Siswa");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Profil Siswa");

        a.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        a.setText("Nis");

        t_nis.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        t_nis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_nisActionPerformed(evt);
            }
        });
        t_nis.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                t_nisKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_nisKeyTyped(evt);
            }
        });

        t_nama.setEditable(false);
        t_nama.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        t_nama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_namaMouseClicked(evt);
            }
        });

        a5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        a5.setText("Nama");

        a1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        a1.setText("Alamat");

        t_alamat.setColumns(20);
        t_alamat.setRows(5);
        jScrollPane1.setViewportView(t_alamat);

        a2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        a2.setText("Jenis Kelamin");

        buttonGroup1.add(l);
        l.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l.setText("Laki_laki");
        l.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        l.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lActionPerformed(evt);
            }
        });

        buttonGroup1.add(p);
        p.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        p.setText("Perempuan");
        p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pActionPerformed(evt);
            }
        });

        a4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        a4.setText("Tanggal Lahir");

        a3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        a3.setText("No.Hp");

        t_hp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btn_insert.setBackground(new java.awt.Color(0, 204, 0));
        btn_insert.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_insert.setText("save");
        btn_insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insertActionPerformed(evt);
            }
        });

        btn_insert1.setBackground(new java.awt.Color(255, 255, 255));
        btn_insert1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_insert1.setText("cancel");
        btn_insert1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insert1ActionPerformed(evt);
            }
        });

        t_lahir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(222, 222, 222)
                                .addComponent(btn_insert)
                                .addGap(27, 27, 27)
                                .addComponent(btn_insert1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(160, 160, 160)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(a5)
                                    .addComponent(a))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(t_nis, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(t_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(154, 154, 154)
                                .addComponent(a1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(a3)
                                            .addComponent(a4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(t_hp, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(t_lahir, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(a2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(l)
                                        .addGap(24, 24, 24)
                                        .addComponent(p)))))
                        .addGap(0, 154, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_nis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a5)
                    .addComponent(t_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(a1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(l)
                        .addComponent(a2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(a4)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(t_lahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a3)
                    .addComponent(t_hp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_insert1)
                    .addComponent(btn_insert))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(591, 487));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insertActionPerformed
            update();                // TODO add your handling code here:
    }//GEN-LAST:event_btn_insertActionPerformed

    private void btn_insert1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insert1ActionPerformed
        new panelsiswa().show();   
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btn_insert1ActionPerformed

    private void t_nisKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_nisKeyReleased
               // TODO add your handling code here:
    }//GEN-LAST:event_t_nisKeyReleased

    private void t_nisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_nisActionPerformed
        golet();                // TODO add your handling code here:
    }//GEN-LAST:event_t_nisActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
           t_nama.setText(login.nama()); 
           golet();   // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void t_nisKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_nisKeyTyped
       // TODO add your handling code here:
    }//GEN-LAST:event_t_nisKeyTyped

    private void lActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lActionPerformed

    private void pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pActionPerformed

    private void t_namaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_namaMouseClicked
         JOptionPane.showMessageDialog(null,"Untuk mengubah nama hubungi admin");         // TODO add your handling code here:
    }//GEN-LAST:event_t_namaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(edit_siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(edit_siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(edit_siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(edit_siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new edit_siswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a;
    private javax.swing.JLabel a1;
    private javax.swing.JLabel a2;
    private javax.swing.JLabel a3;
    private javax.swing.JLabel a4;
    private javax.swing.JLabel a5;
    private javax.swing.JButton btn_insert;
    private javax.swing.JButton btn_insert1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton l;
    private javax.swing.JRadioButton p;
    private javax.swing.JTextArea t_alamat;
    private javax.swing.JTextField t_hp;
    private javax.swing.JTextField t_lahir;
    private javax.swing.JTextField t_nama;
    private javax.swing.JTextField t_nis;
    // End of variables declaration//GEN-END:variables
}
